name: pet_feeder
description: Evcil Hayvan Otomatik Besleme Sistemi

# Uygulama versiyonu ve meta bilgileri
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth bağlantısı için - daha modern alternatif
  flutter_blue_plus: ^1.4.0
  permission_handler: ^10.4.0
  url_launcher: ^6.1.10
  # Datetime formatlama için
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  
  # Simgeler için
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Uygulamada kullanılan varlıklar (isterseniz ekleyebilirsiniz)
  # assets:
  #   - assets/images/